version: '3.8'

services:
  sqlite:
    image: nouchka/sqlite3
    container_name: sqlite
    volumes:
      - ./timeseries.db:/data/timeseries.db
    command: ["sqlite3", "/data/timeseries.db"]
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network

  go-app:
    build: .
    container_name: go-app
    volumes:
      - .:/app
    depends_on:
      - sqlite
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  grafana-storage: